/*
 * GPL.
 */
package Vista;

import Modelo.Equipo;
import Modelo.EquipoTableModel;
import Modelo.Estado;
import Modelo.EstadoListModel;
import Modelo.EstadoTableModel;
import Modelo.HistorialTableModel;
import Modelo.Item;
import Modelo.ItemTableModel;
import Modelo.Miembro;
import Modelo.Prioridad;
import Modelo.Tipo;
import Modelo.TipoListCellRenderer;
import Modelo.TipoTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ale
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static EstadoTableModel etm=new EstadoTableModel();
    public static TipoTableModel ttm=new TipoTableModel();
    public static EquipoTableModel eqtm=new EquipoTableModel();
    public static ItemTableModel itm=new ItemTableModel();
    public static HistorialTableModel htm=new HistorialTableModel();
    
    ActualizarEstado actualizarEstado=new ActualizarEstado(this,true);
    Prioridad prioridades[]=new Prioridad[3];
    
    public Inicio() {
        initComponents();
        Prioridad baja=new Prioridad("Baja",1);
        prioridades[0]=baja;
        Prioridad normal=new Prioridad("Normal",2);
        prioridades[1]=normal;
        Prioridad urgente=new Prioridad("Urgente",3);
        prioridades[2]=urgente;         
        inicializarTablas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelItems = new javax.swing.JPanel();
        BotonNuevoItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PanelEstados = new javax.swing.JPanel();
        BotonNuevoEstado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstados = new javax.swing.JTable();
        PanelTipos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTipos = new javax.swing.JTable();
        botonNuevoTipo = new javax.swing.JButton();
        PanelEquipos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        PanelHistorial = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seguimiento de Items");
        setResizable(false);

        BotonNuevoItem.setText("Nuevo Item");
        BotonNuevoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoItemActionPerformed(evt);
            }
        });

        tablaItems.setModel(itm);
        tablaItems.addMouseListener(
            new MouseAdapter(){
                public void mouseClicked(MouseEvent e){
                    if (e.getClickCount()==2){

                        actualizarEstado.setItem((Item)itm.getValueAt(tablaItems.getSelectedRow(), 0),tablaItems.getSelectedRow());
                        actualizarEstado.setVisible(true);
                        actualizarEstado.configurar();
                    }
                }
            }
        );
        jScrollPane1.setViewportView(tablaItems);

        jLabel1.setText("Para cambiar al siguiente estado, haga doble click en alguno de los items");

        javax.swing.GroupLayout PanelItemsLayout = new javax.swing.GroupLayout(PanelItems);
        PanelItems.setLayout(PanelItemsLayout);
        PanelItemsLayout.setHorizontalGroup(
            PanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelItemsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BotonNuevoItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        PanelItemsLayout.setVerticalGroup(
            PanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelItemsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoItem)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Items", PanelItems);

        BotonNuevoEstado.setText("Nuevo Estado");
        BotonNuevoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoEstadoActionPerformed(evt);
            }
        });

        tablaEstados.setModel(etm);
        tablaEstados.setEnabled(false);
        jScrollPane2.setViewportView(tablaEstados);

        javax.swing.GroupLayout PanelEstadosLayout = new javax.swing.GroupLayout(PanelEstados);
        PanelEstados.setLayout(PanelEstadosLayout);
        PanelEstadosLayout.setHorizontalGroup(
            PanelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
            .addGroup(PanelEstadosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BotonNuevoEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstadosLayout.setVerticalGroup(
            PanelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonNuevoEstado)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estados", PanelEstados);

        tablaTipos.setModel(ttm);
        tablaTipos.setEnabled(false);
        jScrollPane3.setViewportView(tablaTipos);

        botonNuevoTipo.setText("Nuevo tipo");
        botonNuevoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTiposLayout = new javax.swing.GroupLayout(PanelTipos);
        PanelTipos.setLayout(PanelTiposLayout);
        PanelTiposLayout.setHorizontalGroup(
            PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiposLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonNuevoTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTiposLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        PanelTiposLayout.setVerticalGroup(
            PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiposLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoTipo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tipos", PanelTipos);

        tablaEquipos.setModel(eqtm);
        tablaEquipos.addMouseListener(
            new MouseAdapter(){
                public void mouseClicked(MouseEvent e){
                    if (e.getClickCount()==2){
                        System.out.println(eqtm.getValueAt(tablaEquipos.getSelectedRow(), 0));
                    }
                }
            }
        );
        tablaEquipos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaEquiposFocusGained(evt);
            }
        });
        tablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaEquipos);

        jButton1.setText("Nuevo Equipo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEquiposLayout = new javax.swing.GroupLayout(PanelEquipos);
        PanelEquipos.setLayout(PanelEquiposLayout);
        PanelEquiposLayout.setHorizontalGroup(
            PanelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEquiposLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelEquiposLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelEquiposLayout.setVerticalGroup(
            PanelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEquiposLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Equipos", PanelEquipos);

        tablaHistorial.setModel(htm);
        jScrollPane5.setViewportView(tablaHistorial);

        javax.swing.GroupLayout PanelHistorialLayout = new javax.swing.GroupLayout(PanelHistorial);
        PanelHistorial.setLayout(PanelHistorialLayout);
        PanelHistorialLayout.setHorizontalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelHistorialLayout.setVerticalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", PanelHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicializarTablas(){
        Estado e1=new Estado("Creado");
        Estado e2=new Estado("Finalizado");
        etm.addRow(new Estado[]{e1});
        etm.addRow(new Estado[]{e2});
        ArrayList<Estado> lista= new ArrayList<Estado>();
        lista.add(e1);
        lista.add(e2);
        Tipo t=new Tipo("Revisión",lista);
        String textoEstados="{Creado,Finalizado}";
        ttm.addRow(new Object[]{t,textoEstados});
        //agregar equipos
        Equipo eq=new Equipo("Equipo 1","Desarrollo Web");
        Equipo eq2=new Equipo("Equipo 2","Full Stack");
        eq.setDescripcion("Equipo dedicado al desarrollo web de las apliaciones");
        eq2.setDescripcion("Equipo dedicado al desarrollo completo de aplicaciones");
        ArrayList<Miembro> miembros=new ArrayList<Miembro>();
        ArrayList<Miembro> miembros2=new ArrayList<Miembro>();
        Miembro m1=new Miembro("Fede","Programador");
        Miembro m2=new Miembro("Omar","Redes");
        Miembro m3=new Miembro("Ricardo","FrontEnd");
        Miembro m4=new Miembro("Ale","BackEnd");
        miembros.add(m1);
        miembros.add(m2);
        miembros2.add(m3);
        miembros2.add(m4);
        eq.setMiembros(miembros);
        eq2.setMiembros(miembros2);
        eqtm.addRow(new Object[]{eq,eq.getEspecialidad(),"{Fede, Omar }",eq.getDescripcion()});
        eqtm.addRow(new Object[]{eq2,eq2.getEspecialidad(),"{Ricardo, Ale }",eq2.getDescripcion()});

    }
    
    private void BotonNuevoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoItemActionPerformed
        NuevoItem nuevoItem = new NuevoItem(this,true);
        //obtener tipos SI es que hay  
        if (ttm.getRowCount()<=0) {
            JOptionPane.showMessageDialog(null, "No hay tipos disponibles","Alerta",JOptionPane.ERROR_MESSAGE);
        } else {
            Tipo tipos[]=new Tipo[ttm.getRowCount()];
            for (int i = 0; i < ttm.getRowCount(); i++) {
                //carga los tipos en la lista que utiliza NuevoItem
                Tipo t=(Tipo) ttm.getValueAt(i, 0);
                tipos[i]=t;                
            }
            
            Equipo equipos[]=new Equipo[eqtm.getRowCount()];
            for (int i = 0; i < eqtm.getRowCount(); i++) {
                Equipo e=(Equipo) eqtm.getValueAt(i, 0);
                equipos[i]=e;
            }
            
            nuevoItem.comboPrioridades.setModel(new DefaultComboBoxModel(prioridades));
            nuevoItem.comboTipos.setModel(new DefaultComboBoxModel(tipos));
            nuevoItem.comboEquipos.setModel(new DefaultComboBoxModel(equipos));
            nuevoItem.setComboResponsables(equipos[0]);
            nuevoItem.setVisible(true);
        } 
    }//GEN-LAST:event_BotonNuevoItemActionPerformed

    private void botonNuevoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoTipoActionPerformed

        //si hay estados
        if (etm.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No hay estados disponibles para crear tipo","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }else{
        EstadoListModel listModel=new EstadoListModel();
        //EstadoListModel listModel=EstadoListModel.getInstance();
        //Estado e;
        //la clave esta en el etm y como manejarlo, enviarlo como argumento y obtener sus datos
       
        for (int i = 0; i < etm.getRowCount(); i++) {
            //carga los estados en la lista que utiliza NuevoTipo
            listModel.addElement(etm.getValueAt(i, 0));            
        }
        
        //inicia el jdialog
        NuevoTipo nuevoTipo = new NuevoTipo(this, true);
        nuevoTipo.listaEstados.setModel(listModel);
        nuevoTipo.setVisible(true);}
    }//GEN-LAST:event_botonNuevoTipoActionPerformed

    private void BotonNuevoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoEstadoActionPerformed
        NuevoEstado nuevo=new NuevoEstado(this,true);
        nuevo.setVisible(true);
    }//GEN-LAST:event_BotonNuevoEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoEquipo nuevoEquipo=new NuevoEquipo(this,true);
        nuevoEquipo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquiposMouseClicked

    }//GEN-LAST:event_tablaEquiposMouseClicked

    private void tablaEquiposFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaEquiposFocusGained

    }//GEN-LAST:event_tablaEquiposFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNuevoEstado;
    private javax.swing.JButton BotonNuevoItem;
    private javax.swing.JPanel PanelEquipos;
    private javax.swing.JPanel PanelEstados;
    private javax.swing.JPanel PanelHistorial;
    private javax.swing.JPanel PanelItems;
    private javax.swing.JPanel PanelTipos;
    private javax.swing.JButton botonNuevoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTable tablaEstados;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTable tablaItems;
    private javax.swing.JTable tablaTipos;
    // End of variables declaration//GEN-END:variables
}
