/*
 * GPL.
 */
package Vista;

import Controlador.TipoController;
import Modelo.Estado;
import Modelo.Tipo;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ale
 */
public class NuevoTipo extends javax.swing.JDialog {

    private ArrayList<Estado> estadosElegidos = new ArrayList<Estado>();
    private TipoController tipocontroller=TipoController.getInstance();

    public NuevoTipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        botonCrearTipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEstados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Tipo");

        jLabel1.setText("Nombre:");

        botonCrearTipo.setText("Crear Tipo");
        botonCrearTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearTipoActionPerformed(evt);
            }
        });

        listaEstados.setToolTipText("");
        listaEstados.setName(""); // NOI18N
        jScrollPane1.setViewportView(listaEstados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrearTipo))
                        .addGap(0, 139, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(botonCrearTipo)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearTipoActionPerformed

        if(listaEstados.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Debes seleccionar por lo menos un estado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }else if(textTipo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Completa el nombre del tipo","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }else{            

            //se obtienen los indices seleccionados y se utilizan para obtener los estados
            int[] estadosSeleccionados=listaEstados.getSelectedIndices();
            for (int i = 0; i < estadosSeleccionados.length; i++) {

                Estado e= (Estado) Inicio.etm.getValueAt(estadosSeleccionados[i],0);
                estadosElegidos.add(e);            

            }

            //crea un tipo a partir de los estados y el nombre
            Tipo nuevoTipo = tipocontroller.nuevoTipo(textTipo.getText(), estadosElegidos);
          
            this.setVisible(false);

            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            DeterminarSecuenciaEstados secuenciaEstados = new DeterminarSecuenciaEstados(frame,true);
            secuenciaEstados.setLocationRelativeTo(null);
            secuenciaEstados.ordenarSecuencia(nuevoTipo);
            secuenciaEstados.setVisible(true);
        }
    }//GEN-LAST:event_botonCrearTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoTipo dialog = new NuevoTipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> listaEstados;
    private javax.swing.JTextField textTipo;
    // End of variables declaration//GEN-END:variables
}
